name: $(Build.BuildID)

trigger:
- trunk

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  
  jobs:
  - job: macOs_Windows_Pase
    displayName: 'Build'
    strategy:
      matrix:
        macOS:
          OS: 'Windows'
          vmImageName: 'windows-latest'
        Linux:
          OS: 'macOS'
          vmImageName: 'macOS-latest'
      maxParallel: 2
    pool:
      vmImage: $(vmImageName)
    steps:
    - template: tools/ci/build-extension.yml
      parameters:
        UnitTests: true
        CodeCoverage: false
        
  - job: Linux_Phase
    displayName: 'Build Linux'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: tools/ci/build-extension.yml
      parameters:
        UnitTests: true
        CodeCoverage: true

    - task: TfxInstaller@3
      displayName: Install tfxc-cli
      inputs:
        version: 'v0.7.x'

    - task: PackageAzureDevOpsExtension@3
      displayName: Package extension
      inputs:
        rootFolder: '$(System.DefaultWorkingDirectory)'
        updateTasksVersion: false

    - task: CopyFiles@2
      displayName: Copy vsix to publishing folder
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.vsix'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Extension'
        CleanTargetFolder: true
        OverWrite: true
        flattenFolders: true
        preserveTimestamp: true

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/Extension/'
        artifact: 'Extension'
        publishLocation: 'pipeline'
